# Generated by Django 5.0.2 on 2024-11-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0004_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_autor', models.CharField(blank=True, max_length=255, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
