# Generated by Django 5.0.2 on 2024-11-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0005_autores'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autores',
            name='is_active',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autores',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
