# Generated by Django 5.0.2 on 2024-11-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0006_autores_first_name_autores_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_genero', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_genero', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='autores',
            name='is_active',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
