# Generated by Django 5.0.2 on 2024-11-24 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0008_libros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='id_autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proyecto_adminbd_api.autores'),
        ),
    ]
