# Generated by Django 5.0.2 on 2024-11-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0009_alter_libros_id_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='id_autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
