# Generated by Django 5.0.2 on 2024-11-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0012_alter_libros_id_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliotecarios',
            name='id_bibliotecario',
        ),
    ]
