# Generated by Django 5.0.2 on 2024-11-24 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0013_remove_bibliotecarios_id_bibliotecario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='id_cliente',
        ),
    ]
