# Generated by Django 5.0.2 on 2024-11-24 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0014_remove_clientes_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autores',
            name='id_autor',
        ),
    ]
