# Generated by Django 5.0.2 on 2024-11-24 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0015_remove_autores_id_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generos',
            name='id_genero',
        ),
    ]
