# Generated by Django 5.0.2 on 2024-11-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0016_remove_generos_id_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='id_libro',
        ),
    ]
