# Generated by Django 5.0.2 on 2024-11-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0017_remove_libros_id_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_devol_esperada', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_devol_real', models.CharField(blank=True, max_length=255, null=True)),
                ('id_bibliotecario', models.CharField(blank=True, max_length=255, null=True)),
                ('id_libro', models.CharField(blank=True, max_length=255, null=True)),
                ('id_cliente', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
