# Generated by Django 5.0.2 on 2024-11-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0018_prestamos'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='is_active',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
