# Generated by Django 5.0.2 on 2024-11-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0019_prestamos_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='id',
            new_name='id_libros',
        ),
    ]
