# Generated by Django 5.0.2 on 2024-11-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0020_rename_id_libros_id_libros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='id_libros',
            new_name='id_libro',
        ),
    ]
