# Generated by Django 5.0.2 on 2024-11-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0021_rename_id_libros_libros_id_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='id_cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
