# Generated by Django 5.0.2 on 2024-11-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0022_clientes_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='id_cliente',
        ),
    ]
