# Generated by Django 5.0.2 on 2024-11-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0023_remove_clientes_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='veces_prestado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='prestamos_solicitados',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
