# Generated by Django 5.0.2 on 2024-11-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0024_libros_veces_prestado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='veces_prestado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
