# Generated by Django 5.0.2 on 2024-11-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0025_alter_libros_veces_prestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='prestamos_solicitados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
