# Generated by Django 5.0.2 on 2024-11-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_adminbd_api', '0026_alter_prestamos_prestamos_solicitados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamos',
            name='prestamos_solicitados',
        ),
        migrations.AddField(
            model_name='clientes',
            name='prestamos_solicitados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
